name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: The number of the PR that is being deployed
        required: true
  push:
    branches:
      - main

jobs:
  Publish:
    name: Publish Next to npm
    runs-on: ubuntu-latest
    if: github.repository_owner == 'skyra-project'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add TypeScript problem matcher
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"
      - name: Use Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
          registry-url: https://registry.yarnpkg.com/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Bump Version & Publish
        run: |
          # Resolve the tag to be used. "next" for push events, "pr-{prNumber}" for dispatch events.
          TAG=$([[ ${{ github.event_name }} == 'push' ]] && echo 'next' || echo 'pr-${{ github.event.inputs.prNumber }}')

          yarn config set npmAuthToken ${NODE_AUTH_TOKEN}
          yarn config set npmPublishRegistry "https://registry.yarnpkg.com"

          yarn bump --preid "${TAG}.$(git rev-parse --verify --short HEAD)"

          yarn npm publish --tag ${TAG}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

  Docgen:
    name: Docgen
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Use Node.js v20
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build documentation
        run: yarn docs
      - name: Add static files
        run: |
          printf "User-agent: *\nDisallow:" > docs/robots.txt
          cp .gitignore docs/
          cp LICENSE.md docs/
          cp README.md docs/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
